Use printf in preference to echo

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,7 +3,7 @@
 # Define dotfiles directory and check it exists
 dotfiles="$HOME/.dotfiles"
 if [[ ! -n "$dotfiles" ]]; then
-    echo "Could not find $dotfiles!" >&2
+    printf "Could not find $dotfiles!\n" >&2
     exit 1
 fi
 
