Standardise use of printf

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,7 +3,7 @@
 # Define dotfiles directory and check it exists
 dotfiles=$HOME/.dotfiles
 if [[ ! -d $dotfiles ]]; then
-    printf "Could not find $dotfiles!\n" >&2
+    printf %s "Could not find $dotfiles!\n" >&2
     exit 1
 fi
 
