Hardcode install script name in error output
$0 is unreliable/misleading

diff --git a/install b/install
--- a/install
+++ b/install
@@ -47,14 +47,14 @@ lns() {
 
 # Bail if we don't have git(1)
 if ! hash git 2>/dev/null; then
-    printf '%s: Could not find git(1)!\n' "${0##*/}" >&2
+    printf 'install: Could not find git(1)!\n' >&2
     exit 1
 fi
 
 # Define dotfiles directory and check it exists
 dotfiles=$HOME/.dotfiles
 if [[ ! -d $dotfiles ]]; then
-    printf '%s: Could not find %s!\n' "$dotfiles" "${0##*/}" >&2
+    printf 'install: Could not find %s!\n' "$dotfiles" >&2
     exit 1
 fi
 
