Bracing variable for safety

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,7 +4,7 @@
 dotfiles="$HOME/.dotfiles"
 if [[ ! -n "$dotfiles" ]]
 then
-    echo "Could not find $dotfiles!" >&2
+    echo "Could not find ${dotfiles}!" >&2
     exit 1
 fi
 
